version: "3.9"

services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3308:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Wkfroot
      MYSQL_DATABASE: my_database

  tomcat:
    image: tomcat:10.1.6-jdk17-temurin
    ports:
      - "8082:8080"
    volumes:
      - /app/tomcat/webapps:/usr/local/tomcat/webapps
    environment:
      TZ: Asia/Shanghai
    depends_on:
      mysql:
        condition: service_healthy  //依赖mysql先启动
