
version: '3.8'  # 指定 Docker Compose 文件的版本,去官网查docker对应的Docker Compose版本

services:  # 定义服务
  db:  # 定义名为 db 的服务，通常是数据库服务
    image: mysql:8.0.27  # 使用 MySQL 8.0.27 镜像
    container_name: my_mysql_container  # 容器的名称为 my_mysql_container
    environment:  # 环境变量，用于配置 MySQL
      MYSQL_ROOT_PASSWORD: Wkfroot  # MySQL root 用户的密码
      MYSQL_DATABASE: my_database  # 初始化时创建的数据库名称
      MYSQL_USER: wkf  # 新建的 MySQL 用户名
      MYSQL_PASSWORD: Wkfuser  # 新建的 MySQL 用户的密码
      TZ: Asia/Shanghai  # 设置容器的时区为上海时间
    ports:
      - "3306:3306"  # 将容器的 3306 端口映射到主机的 3306 端口
    volumes:  # 定义挂载卷
      - ./ db_data:/var/lib/mysql  # 将名为 db_data 的卷挂载到容器的 /var/lib/mysql 目录，用于持久化数据
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 将当前目录下的 init.sql 文件挂载到容器的 /docker-entrypoint-initdb.d/init.sql 目录，用于初始化数据库数据

  web:  # 定义名为 web 的服务
    image: tomcat  # 使用 Tomcat镜像
    container_name: my_tomcat_container  # 容器的名称
    ports:
      - "8080:8080"  # 映射 Tomcat 端口
    volumes:  # 定义挂载卷
      - ./webapps:/usr/local/tomcat/webapps  # 将 webapps 目录挂载到主机

volumes:  # 定义卷
  db_data:  # 创建一个名为 db_data 的卷，用于持久化 MySQL 数据
..